name: Deploy Surge

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
          
      - name: Install Surge
        run: npm install -g surge
      - name: Run Surge
        run: surge ./ bootcampnewapp.surge.sh ---token ${{secret.SURGE_TOKEN}}
